version: "2.1"
services:
  app_proxy:
    environment:
      APP_HOST: $APP_MINETEST_SERVER_IP
      APP_PORT: $APP_MINETEST_SERVER_PORT
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS="--gameid minetest --port 30000" #optional
    volumes:
      - ${APP_DATA_DIR}:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
    networks:
      default:
        ipv4_address: $APP_MINETEST_SERVER_IP